### ISSUE TITLE
Trouble parsing Twarc dump

### ISSUE THREAD

**Issue by weberdc** [behavioral-ds/BirdSpotter#1]
I'm trying to use birdspotter from the commandline on Windows under Anaconda 3, and it can't seem to parse the tweets I've collected using Twarc. The output is the following (NB the first six lines are repeated many times (as many times as there are tweets, perhaps?)):

<pre>  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\birdspotter\BirdSpotter.py", line 184, in extractTweets
    temp_content = {'status_text':j['text'], 'user_id' : j['user']['id']}
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\birdspotter\BirdSpotter.py", line 184, in extractTweets
    temp_content = {'status_text':j['text'], 'user_id' : j['user']['id']}
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\birdspotter\BirdSpotter.py", line 184, in extractTweets
    temp_content = {'status_text':j['text'], 'user_id' : j['user']['id']}
Traceback (most recent call last):
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\Scripts\birdspotter", line 30, in <module>
    bs = BirdSpotter(dumpPath, quiet=quiet)
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\birdspotter\BirdSpotter.py", line 55, in __init__
    self.extractTweets(path,  tweetLimit = tweetLimit, embeddings=embeddings)
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\birdspotter\BirdSpotter.py", line 241, in extractTweets
    userDataframe = pd.DataFrame(user_list).fillna(0).set_index('user_id')
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\pandas\core\frame.py", line 4178, in set_index
    level = frame[col]._values
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\derek\Documents\tools\Anaconda3\envs\election\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_id'
</pre>

Looking at the BirdSpotter code, it's not immediately clear why this is being thrown. The property `.user.id` is valid in the tweets, but the property `.text` is not - instead it's `.full_text` in this dataset (collected over the last couple of weeks - perhaps APIs have changed). Maybe that's the real issue.

This fails on a single tweet too (first of the collection).

Any tips on how I can get this up and running? 

Thanks.

D.

**Comment by rohitram96** [comment]
@weberdc twarc seems to use the `extended_mode` by default, which results in `full_text` as opposed to `text`. 

Thanks for flagging this, it requires a fix. I'll make some changes and update this thread.

This seems to be the only consequence of `extended_mode` which would impact `birdspotter`. So a workaround, in the meanwhile, would be to create a copy of your dump with `full_text` replaced with `text`.

I'll let you know when there is a proper fix though.

**Comment by rohitram96** [comment]
The commit 1284c78c353df8017251ee027acf27c7eb8a3a6f contains a wheel in the `./dist` folder which fixes this. You can clone the repo and do `pip install *.whl` to use that version.

It'll also be added to the next release.

**Comment by weberdc** [comment]
Thanks for the pointers - I used the rename .full_text to .text trick to get a bit further, but am still having a little trouble, now on a Mac, not just on Windows 10. Can you tell me if this error is related, or should it be a different Issue:

`(election) derek@orac ➜  arson ~/Library/Python/3.7/bin/birdspotter -i one_tweet.json -o botscores/overall
Starting Tweet Extraction
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/derek/Library/Python/3.7/bin/birdspotter", line 30, in <module>
    bs = BirdSpotter(dumpPath, quiet=quiet)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 55, in __init__
    self.extractTweets(path,  tweetLimit = tweetLimit, embeddings=embeddings)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 241, in extractTweets
    userDataframe = pd.DataFrame(user_list).fillna(0).set_index('user_id')
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 4411, in set_index
    raise KeyError("None of {} are in the columns".format(missing))
KeyError: "None of ['user_id'] are in the columns"
(election) derek@orac ➜  arson cat one_tweet.json| jq -rc '.user.id_str'
894082981534384129
(election) derek@orac ➜  arson cat one_tweet.json| jq -rc '.user.id'
894082981534384100
(election) derek@orac ➜  arson cat one_tweet.json| jq -rc '.id_str'
1211893587702497280
(election) derek@orac ➜  arson cat one_tweet.json| jq -rc '.id'
1211893587702497300`

I thought I'd try looking at the user id and tweet id fields, and found that the id and id_str values are different, which I didn't expect. I use id_str in all my code, just to ensure I don't get rounding errors, but I'm not sure if it's absolutely necessary - do these results imply it is?

This is all using one tweet, which I'll attach as txt.
[one_tweet.json.txt](https://github.com/behavioral-ds/BirdSpotter/files/4120232/one_tweet.json.txt)

**Comment by rohitram96** [comment]
I think this is a new issue. I'll have to do a little digging to confirm and will get back to you shortly. Notably in the new wheel we use 'id_str', as it's recommended by Twitter.

I'll post back here when I have more information.

**Comment by rohitram96** [comment]
@weberdc I think I can replicate this error partially, but not in full on my machine. 

Could you try renaming `one_tweet.json` to `one_tweet.jsonl` and let me know what the output is.

**Comment by weberdc** [comment]
I'll start a new issue, but think I've found a way through: change the suffix to jsonl and the output needs to be a file, not a directory (which is what I guessed from the birdspotter script).

**Comment by weberdc** [comment]
Shiftted to #2.

**Comment by rohitram96** [comment]
`birdspotter` now handles both modes now.
